version: '3.8'

services:
 web:
  build:
   context: .
  ports:
  - 5000:5000
  volumes:
  - ./:/app

 mariadb:
  image: mariadb
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - mariadb:/var/lib/mariadb
  - mariadb_config:/etc/mariadb

volumes:
  mariadb:
  mariadb_config: